# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02357b70cd26ad226c6d99ad3455d9aa66a531c0297c5741dbfb7dff0e906cd2ed893350fa8e5a5532a47ff3038a2dd661a29ec865aa7180e0a9d5a8035d8c87

test:
  secret_key_base: 25010ab5b2b173cad208def93b3110cfd4d6a0abd5cd06dc4787d7d6b3d838dc3704a89136adba0ede4fe4863448f731607350b3ba500edac2cc7627e316f557

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
